[build]
builder = "nixpacks"

[deploy]
startCommand = "bun dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
healthcheckInterval = 30

[deploy.preDeploy]
command = "bun run db:migrate:prod" 